# Generated by Django 4.0.5 on 2023-03-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=300)),
                ('publish_date', models.DateField()),
            ],
        ),
    ]
#